---
#- name: stop tomcat
#  notify:
#   - stop tomcat service
- name: stop tomcat service
  shell: "ps -ef |grep {{ tomcat_service_dir }} |grep -v grep |awk '{print $2}'|xargs kill -9"

- name: deploy tomcat
  script: /xxdata/scripts/tomcat-deploy.sh
- name: rm old app_name
  file: path={{ tomcat_service_dir }}/webapps/{{ app_name }} state=absent
- name: rm old app_name.war
  file: path={{ tomcat_service_dir }}/webapps/{{ app_name }}.war state=absent
- name: copy  newapp.war
  shell: cp /xxdata/build/{{ app_name }}.war {{ tomcat_service_dir }}/webapps
- name: unzip war
  shell: unzip {{ tomcat_service_dir }}/webapps/{{ app_name }}.war -d {{ tomcat_service_dir }}/webapps/{{ app_name }}
  notify:
    - start tomcat service

#- include: evaluation.yml  project=evaluation

#- include: examcenter.yml project=examcenter


#- name include stop tomcat yml
#  include:stoptomcat.yml
#  when:"state=='stopped'"
